apiVersion: privileged.azuread.upbound.io/v1beta1
kind: AccessGroupEligibilitySchedule
metadata:
  annotations:
    meta.upbound.io/example-id: privileged/v1beta1/accessgroupeligibilityschedule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    assignmentType: member
    duration: P30D
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pim
    justification: as requested
    principalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: member

---

apiVersion: groups.azuread.upbound.io/v1beta2
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: privileged/v1beta1/accessgroupeligibilityschedule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: group-name
    securityEnabled: true

---

apiVersion: users.azuread.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: privileged/v1beta1/accessgroupeligibilityschedule
  labels:
    testing.upbound.io/example-name: member
  name: member
spec:
  forProvider:
    displayName: J. Doe
    mailNickname: jdoe
    passwordSecretRef:
      key: credentials
      name: example-secret
      namespace: upbound-system
    userPrincipalName: testuser_upbound.io#EXT#@devopsupbound.onmicrosoft.com

---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
stringData:
  credentials: SecretP@sswd99!
